- name: ssh keys to root accounts
  hosts: all
  ignore_unreachable: true
  tasks:
    - name: put all keys to user
      ansible.posix.authorized_key:
        user: "{{ user }}"
        exclusive: yes # remove other keys
        state: present
        key: "{{ key }}"