- name: deply ssh keys calling 'distribute-ssh-keys-for-user-if-exists.yaml' setting vars 'username' and 'ssh_keys'
  include_tasks: distribute-ssh-keys-for-user-if-exists.yaml
  loop: "{{ ssh_users | dict2items }}"
  loop_control:
    loop_var: user
  vars:
    username: "{{ user.key }}"
    # read ssh keys from given file user.value.ssh_keys_file
    ssh_keys: "{{ lookup('file', user.value.ssh_keys_file).split('\n') }}"

