- name: debug ssh users
  debug:
    msg: "User {{ item.key }} has keys {{ item.value.ssh_keys }}"
  loop: "{{ ssh_users | dict2items }}"

- name: deploy ssh keys
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ item.value.ssh_keys | join('\n')}}"
  loop: "{{ ssh_users | dict2items }}"
