- name: docker-compose up all services
  debug:
    msg: "docker-compose up -d"

- name: bring up all services
  docker_compose:
    project_src: "services/{{ item }}"
    state: present
  loop: "{{ projects_dirs }}"
