- name: Copy services folder to remote host
  synchronize:
    src: "{{ local_services_path }}/"
    dest: "{{ remote_services_path }}"
    delete: yes
    recursive: yes
  delegate_to: localhost

- name: Ensure privacy of remote services directory
  file:
    path: "{{ remote_services_path }}"
    state: directory
    mode: '0700'

