- name: Ensure remote services directory exists
  file:
    path: "{{ remote_services_path }}"
    state: directory
    mode: '0755'

- name: Copy services folder to remote host
  synchronize:
    src: "{{ local_services_path }}/"
    dest: "{{ remote_services_path }}"
    delete: yes
    recursive: yes
  delegate_to: localhost

