- name: install apt packages "{{ apt_packages_to_install | default([])}}"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ apt_packages_to_install | default([]) }}"
    state: present