- name: "Download Adoption Temurin 21 from {{ temurin_jdk_21_url }} to {{ temurin_21_parent }}/{{ temurin_21_local_file }}"
  ansible.builtin.get_url:
    url: "{{ temurin_jdk_21_url }}"
    dest: "{{ temurin_21_parent }}/{{ temurin_21_local_file }}"

- set_fact:
    openjdk_21_target: "{{ temurin_21_parent }}/openjdk-21"

- name: delete OpenJDK-21 target directory {{ openjdk_21_target }}
  ansible.builtin.file:
    path: "{{ openjdk_21_target }}"
    state: absent

- name: create OpenJDK-21 target directory {{ openjdk_21_target }}
  ansible.builtin.file:
    path: "{{ openjdk_21_target }}"
    state: directory

- name: unarchive OpenJDK-21
  ansible.builtin.unarchive:
    src: "{{ temurin_21_parent }}/{{ temurin_21_local_file }}"
    dest: "{{ openjdk_21_target }}"
    remote_src: yes
    extra_opts: "--strip-components=1"