- name: create folder '~/bin' if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/weak_conditional_shutdown_v1"
    state: directory
    mode: '0755'

- name: copy script to ~/weak_conditional_shutdown_v1
  copy:
    src: "weak_conditional_shutdown_v1.sh"
    dest: "{{ ansible_env.HOME }}/weak_conditional_shutdown_v1/weak_conditional_shutdown_v1.sh"
    mode: '0755'
