- name: create dir to_print
  ansible.builtin.file:
    path: /var/tmp/to_print
    state: directory
    mode: '0755'

- name: create dir printed
  ansible.builtin.file:
    path: /var/tmp/printed
    state: directory
    mode: '0755'

- name: create dir print_fails
  ansible.builtin.file:
    path: /var/tmp/print_fails
    state: directory
    mode: '0755'

