- name: "Create mountpoint for {{ item.mountpoint }}"
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
    mode: "0755"

- name: "Mount {{ item.mountpoint }}"
  ansible.posix.mount:
    src: "{{ item.storage }}"
    path: "{{ item.mountpoint }}"
    opts: rw,async
    boot: yes
    state: mounted
    fstype: nfs
